kind: pipeline
name: docker-build
type: docker

steps:
  - name: build
    image: loongcr.lcpu.dev/lcpu/archlinux:base
    volumes:
    - name: dockersock
      path: /var/run/docker.sock
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
    - pacman -S --noconfirm docker
    - docker build -t loongcr.lcpu.dev/repository/drone/drone-runner-docker:latest ./docker/Dockerfile.linux.loong64
    - docker login -u="\$app" -p="$DOCKER_PASSWORD" loongcr.lcpu.dev
    - docker push loongcr.lcpu.dev/repository/drone/drone-runner-docker:latest

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
