kind: pipeline
name: docker-build
type: docker

steps:
  - name: build
    image: loongcr.lcpu.dev/lcpu/archlinux:base
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
    - pacman -Sy --noconfirm && pacman -S --noconfirm podman
    - podman build -t loongcr.lcpu.dev/drone/drone-runner-docker:latest -f ./docker/Dockerfile.linux.loong64 .
    - podman login -u="\$app" -p="$DOCKER_PASSWORD" loongcr.lcpu.dev
    - podman push loongcr.lcpu.dev/drone/drone-runner-docker:latest
